# Generated by Django 4.0.3 on 2022-05-21 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='avatar.png', null='True', upload_to=''),
            preserve_default='True',
        ),
    ]
